[profile.default]
src = "contracts/src"
out = "out"
libs = ["contracts/lib"]
solc_version = "0.8.23"
optimizer = true
optimizer_runs = 200
via_ir = true
gas_reports = ["*"]
gas_reports_ignore = []

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
base = "${BASE_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
bsc = "${BSC_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
arbitrum = { key = "${ARBISCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}" }
polygon = { key = "${POLYGONSCAN_API_KEY}" }
bsc = { key = "${BSCSCAN_API_KEY}" }
optimism = { key = "${OPTIMISM_API_KEY}" }

[profile.ci]
fuzz = { runs = 10_000 }
invariant = { runs = 10_000, depth = 15, fail_on_revert = false } 